// Generated by CoffeeScript 2.1.1
var generate, getName, request;

request = require('sync-request');

getName = function(times) {
  var name, res;
  times = parseInt(times);
  if (isNaN(times)) {
    throw Error('times must be a number');
  }
  res = request('GET', 'https://www.switchplane.com/_project/ajax-business-name-generator.php');
  name = JSON.parse(res.getBody().toString()).data;
  if (times === 1) {
    return name;
  }
  return name + '|' + getName(times - 1);
};

generate = function(times = 1) {
  return (getName(times)).split('|');
};

module.exports = generate;
